### ISSUE TITLE
Test cases failing: ReferenceError: AmCharts is not defined

### ISSUE THREAD

**Issue by vikramgupta1988** [amcharts/amcharts3-react#88]
While running testcases using Jest and Enzyme. I get an error like below.

`ReferenceError: AmCharts is not defined
      at node_modules/@amcharts/amcharts3-react/amcharts3-react.js:253:3
      at Object.<anonymous> (node_modules/@amcharts/amcharts3-react/amcharts3-react.js:298:3)
      at Object.<anonymous> (node_modules/@amcharts/amcharts3-react/index.js:6:3)`

The AmCharts are imported in my project like below
`import AmCharts from '@amcharts/amcharts3-react'`

I found a solution that is to be added to amcharts-react plugin at line 252.
`var AmCharts = AmCharts || {};`
This is solving the issue. Can I create a PR for this?

Or alternatively can we ignore the import while running the test case?

**Comment by darlesson** [comment]
I would recommend the use of [setupFiles](https://jestjs.io/docs/en/configuration.html#setupfiles-array) to inject amCharts files to the environment.
